### ISSUE TITLE
How to run test_etsumm

### ISSUE THREAD

**Issue by him-28** [esmf-org/esmf-test-scripts#16]
@bekozi  : Can you simplify the Readme I cannot figure out how to run test_etsumm . There is a bug in the code which I need to test but I can't figure out how to run test_etsumm just to check how a test case will work , mpiuni case doesn't have comm_version and the code should have an if -else for mpiuni .

**Comment by bekozi** [comment]
The idea was to assign a version to mpiuni. We discussed in a meeting. Let
me know if it continues to fail after assigning a version. Make it 0.1 or
whatever you want.
