### ISSUE TITLE
Add ESMPy testing to Argus

### ISSUE THREAD

**Issue by rokuingh** [esmf-org/esmf-test-scripts#17]
ESMPy depends on the ESMF shared library, which can be had via ESMF installation. ESMPy is installed via:

`python setup.py --ESMFMKFILE <PATH_TO_ESMFMK> --prefix <INSTALL_PATH>`

After building ESMPy, the testing is run with:

```
python setup.py test
python setup.py test_examples
```

If mpi is available there are also parallel test targets:

```
python setup.py test_parallalel
python setup.py test_examples_parallel
```

This would be a great start towards full ESMPy testing. There are other targets that could be testing in future or modified to fit the needs of this workflow.

**Comment by mark-a-potts** [comment]
Hey Ryan,

I can't seem to get the setup.py test to run at all. I get the following error when running from the ESMFpy directory after building and installing--

python setup.py test
running test
error: [Errno 2] No such file or directory

The test_examples give me an error with the download not being available. Is that expected for the 8.0.2 branch?

**Comment by rokuingh** [comment]
For the first one, have you already built ESMPy?

`python setup.py build --ESMFMKFILE <PATH_TO_ESMFMK>`

For the second one, are you calling this from a batch job? You often need to use a dryrun command on the login node to download the files in this scenario. Another thing you can do is run the examples in serial on the login node once first.

`python setup.py test_examples_dryrun`

**Comment by mark-a-potts** [comment]
I can build and install, but I am currently hitting an issue with the pull of data. Did the URL change?

python setup.py test_examples_dryrun
running test_examples_dryrun
Retrieving http://www.earthsystemmodeling.org/download/data/aggregAtlanticESTOFS.nc...

Error opening http://www.earthsystemmodeling.org/download/data/aggregAtlanticESTOFS.nc
error: Error downloading 'aggregAtlanticESTOFS.nc'

**Comment by rokuingh** [comment]
I fixed the data download links yesterday, have you fetched the recent changes?

**Comment by rsdunlapiv** [comment]
Should be:
http://data.earthsystemmodeling.org/download/data/aggregAtlanticESTOFS.nc

**Comment by ryanlong1004** [comment]
completed previously (pythontest feature).
