### ISSUE TITLE
"Dry run" or sanity check for build-test.py

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#19]
Since the build takes a long time in ESMF, it can take a long time during the build/test process before you know that your environment (e.g., modules) are not set up correctly.

It would be nice to have a "dry run" option in the script that would load the modules from the YAML config file and attempt to build and run a very small MPI application using the selected compiler/MPI.  This sanity check option could be used while developing the YAML file to determine the set of valid module combinations.

The option could also run directly on the login node (not use the queue) since the user will want immediate feedback.

**Comment by rokuingh** [comment]
In the past we have reserved "dry run" for downloading data files. Also, on some platforms (like Cheyenne) you cannot run mpiexec on login nodes. Maybe this request might be more aligned with a "check" option that just runs a super light version, i.e. one single mpi test on the compute node, but still requiring a batch submission.

**Comment by rsdunlapiv** [comment]
Here is an example of why this is needed:
https://github.com/esmf-org/esmf-test-artifacts/commit/5dcad22f163a2de4ac7230a56170ebf4dbf6cdd4

A first pass implementation of this feature would be to try to load the module sets specified in the YAML file and make sure that all modules load correctly.  The result should be reported immediately back to the user.  This would allow the user to validate that their YAML file is at least expected to load the correct modules.  Without this, we would likely lose a night of testing since we might not get the error until after waiting in the queue for a long time.

It could be extended later to try to compile a small application with the current modules.  The big idea is to maximize the chance that the YAML file will work the first time.

**Comment by ryanlong1004** [comment]
completed previously
