### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by bekozi** [esmf-org/esmf-test-scripts#2]
Currently Python 2.7 is a requirement and this should be migrated to Python 3. If Python 2.7 is a platform requirement somewhere, we should use `six` for backwards compatibility.

**Comment by him-28** [comment]
I just ran the milestone 1 with Python 3 and it ran successfully but I will make sure future milestones should be Python 3 compatible .

**Comment by bekozi** [comment]
That's good news. I'll close the ticket!
