### ISSUE TITLE
Push test artifacts to https://github.com/esmf-org/esmf-test-artifacts

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#21]
Test artifacts should be collected in this repository using the existing directory structure:
https://github.com/esmf-org/esmf-test-artifacts/tree/master/develop

Example of directory structure:
`develop/orion/intel/19.1.0.166/g/intelmpi/2020`

We need to determine what artifacts need to be pushed.  Build/test stdout/stderr are critical as is the summary.  Having all the Log and stdout from all the unit, system, examples requires pushing more content, but is helpful for developers to see details of failing tests.

**Comment by rsdunlapiv** [comment]
The script should be flexible enough to automatically push to a subdirectory with the same branch/tag name as the tested branch/tag.

**Comment by rsdunlapiv** [comment]
@mark-a-potts test artifacts from your runs are currently going to the python branch: https://github.com/esmf-org/esmf-test-artifacts/tree/python.

Can you please switch those artifacts to commit to `master`?  We can then remove the python branch.

At some point we need to rename `master` to `main` as well.

**Comment by mark-a-potts** [comment]
The artifacts actually get pushed to whatever branch esmf-test-artifacts currently has checked out. I recently switched Hera and Orion over to master, so they should be pushing there now.

**Comment by mark-a-potts** [comment]
This is now in place.
