### ISSUE TITLE
Support ESMF testing on machines without a batch queuing system

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#23]
Not all of our platforms use Slurm, PBS, etc.   The test script should support running the script in an interactive mode, directly in the current shell (or background process), and push results to esmf-test-artifacts in the usual way.

**Comment by mark-a-potts** [comment]
I think this will work now. I have an example file for a machine with modules, but no batch system (chianti.yaml) and another example for a machine with no modules and no batch system (chianti-no-modules.yaml). Note that there is a kludge required for the yaml entry for the mpi module. It can really say anything other than "None", which confuses the script into thinking it is running mpiuni. So, in the chianti-no-modules.yaml file, I make it "NoModule".  I am not entirely sure all the environment variables are required. That will require further testing.

**Comment by rsdunlapiv** [comment]
@mark-a-potts great - thanks!

@him-28 can you please try to convert over one of the remaining platforms without a batch system to use the script, based on the example yaml files from @mark-a-potts?

**Comment by him-28** [comment]
Trying this on Bighorn @rsdunlapiv  @mark-a-potts

**Comment by rsdunlapiv** [comment]
Any update @him-28?

Please proceed with moving *all* platforms over to the Python script.

**Comment by him-28** [comment]
@rsdunlapiv  I am running all the platform using the Python Script and will give you an update tomorrow morning

**Comment by mark-a-potts** [comment]
This seems to be working in general now. Any specific issues should be a new ticket.
