### ISSUE TITLE
Support testing of pull request branches

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#24]
If a code contribution comes in from the community (someone outside the core team) we need a simple mechanism by which platforms can be switched over to test PR branches.  One option here is to add a particular label to the PR and have the testing scripts running on each platform use the GitHub CLI (or http request) to pull in the list of PRs and look for a given label.  

This would allow external users to see the results of their code change on multiple platforms.

This has to be balanced against core hour usage, etc.  We will not be able to test every PR across all platforms, but might want to systematically turn a few own before merging the PR into develop.

**Comment by mark-a-potts** [comment]
I have added in a branch: section to the yaml file, but I am not sure if that will work with a PR or not. It would work with their branch, though.

**Comment by rsdunlapiv** [comment]
The use case here is that a user submits a PR and we'd like to switch over some of the platforms to test the associated branch.  Ideally, by pushing a change to the esmf-test-scripts yaml files, it should affect the branch tested on remote platforms.  It would even allow an ESMF team member to change the tested branch on a platform that they cannot access.

**Comment by mark-a-potts** [comment]
This should work for any platform that is on a crontab or is pulling the latest from esmf-test-scripts before running the scripts.  The run_esmf_tests_XXX.sh scripts I have been putting into the branch cd to the location of esmf-test-scripts, pull the latest from the python branch, and then launch the testing framework. So, changing the yaml file for a machine or two would propagate out to those machines on the next iteration.

**Comment by ryanlong1004** [comment]
completed previously
