### ISSUE TITLE
ESMF_NETCDF=nc-config

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#26]
When NetCDF module is loaded, then the ESMF_NETCDF=nc-config needs to be set.  This will find it in the path and enable the build and testing with NetCDF.

Some platforms might need to ESMF_NETCDF=nc-config and ESMF_NFCONFIG=nf-config.

**Comment by rsdunlapiv** [comment]
@mark-a-potts can this be closed?

**Comment by mark-a-potts** [comment]
Done.
