### ISSUE TITLE
Getting Job ID and curbing its behavior with cmd 

### ISSUE THREAD

**Issue by him-28** [esmf-org/esmf-test-scripts#29]
Job ID using sacct/qstat/squeue .
Also the script is displaying job ID on cmd till the job ends and is interfering with cmd .

**Comment by rsdunlapiv** [comment]
@him-28 please put specific parameters that are now working (e.g., --qos, etc.)

For qstat -H, please provide working combination.

**Comment by him-28** [comment]
For example : qstat -H {} will not work in Izumi I replaced it with `qstat -u $USER | tail -n 1 | awk -F ' +' '{{print $1}}' | sed 's/.izumi.unified.u//'`
