### ISSUE TITLE
Scripts need a meaningful name and should use a shebang

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#3]
The "milestone1.py" scripts needs a meaningful name.  I am in favor of using a shebang at the top of scripts and omitting the ".py" extension.  
https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take
@bekozi what do you think?

**Comment by bekozi** [comment]
This is okay to do. Typically, the original Python file exists somewhere in `src` and it's during the `python setup.py install` phase that the file is renamed (see the [ocgis setup.py](https://github.com/NCPP/ocgis/blob/master/setup.py#L118) for an example). 

I'm not sure the program will have a setup step, but I do recommend it. You can add test targets, etc. and handle a lot of the platform configuration during this. It is very standard for Python packages. Probably, we'll need a milestone for packaging testing scripts using a standard Python approach.

**Comment by rsdunlapiv** [comment]
@bekozi does setuptools itself require a separate installation?  I am not opposed to a setup step, but it needs to be highly portable.

We also need to think about how to handle updates to the testing infrastructure itself.  Will updates be pulled in automatically, e.g., a fresh set of scripts are "git pulled" each night on a regularly tested platform?  If so, would we need to run the setup script again to update the installation?  We probably need to do some thinking about what kinds of changes can be pulled in automatically and what kinds require manual steps on a given platform.  

Example use case:  we want to add a new compile time flag to all platforms testing Intel versions 18+. This should be done without having to log in to each platform.

**Comment by bekozi** [comment]
> Example use case: we want to add a new compile time flag to all platforms testing Intel versions 18+. This should be done without having to log in to each platform.

This is further impetus for working from YAML or JSON from the start!

@rsdunlapiv brings up a good point that the Python test program should be self-updating. Once it is installed logging in is only required for critical maintenance.
