### ISSUE TITLE
Capture build and test output and suppress standard out

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#4]
The stdout of the build and all_tests target needs to be captured.  This could be captured in separate files in a "logs" directory.

During execution of the script, it is hard to see overall progress since all of the build/test output is dumped to the screen.  The default behavior could be to suppress this output and just provide simple status indicators:

Example:
```
Cloning ESMF.... complete
Building ESMF .... complete
Running all_tests target .... complete
Uploading results ..... complete
```

It's also nice to know that things are still running, not hanging, especially for long running commands.  This could perhaps be indicated by printing a "." every 10 seconds for long running commands.

**Comment by rsdunlapiv** [comment]
An option could be provided to the script as to whether to suppress standard out of the make commands, e.g.

```
./run-esmf-tests --verbose
```

**Comment by bekozi** [comment]
We really should consider using [click](https://click.palletsprojects.com/en/7.x/) for the CLI. It will save a lot of work and make the end product much more usable in my opinion. The [`ocli`](https://github.com/NCPP/ocgis/blob/master/src/ocgis/ocli.py) CLI has good examples of click usage (with subcommands).

**Comment by rsdunlapiv** [comment]
@bekozi I know I sound like a broken record, but how will we handle the installation of click itself?  

If there is one way to package up everything and have it run everywhere, then I am happy to use these external libraries.  Is there a general solution to this that works across the board?  If we think there is one, then we need to assemble a package and test it on a wide range of platforms.

**Comment by bekozi** [comment]
I would be surprised if we could not create a Python virtual environment on the login node on all platforms. If not, we could package these dependencies as submodules I expect. @him-28 could try creating a simple venv on platforms he has access to by following: https://docs.python.org/3/tutorial/venv.html.

We could test `pip install click setuptools` using the venv. I think it is worth investigating some additional simple installation requirements to avoid creating a lot of boilerplate code. In the end, it may not be possible to use these but will save time and create simpler / more robust code if it is.

**Comment by rsdunlapiv** [comment]
It seems critical to determine in the short term how we plan to set up the actual Python environment itself as that will determine whether @him-28 can use external dependencies (which will make development much easier and robust) or whether we have to keep things to core Python 3.  I recommend @him-28 determine our best options and we test those broadly on a range of platforms in order to make a decision.
