### ISSUE TITLE
Delete prior artifacts when a new build is pushed

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#41]
We currently have a two-phase push to esmf-test-artifacts: (1) after the build and (2) after the tests run.

Between (1) and (2) the test artifacts repo is in an inconsistent state since only the build log is updated, while the older test results remain.  See timestamps below:

![image](https://user-images.githubusercontent.com/3218838/110995120-0ed1c300-8337-11eb-9146-a788190ad586.png)

Once a new build phase has started, all the prior artifacts should be deleted so there is no confusion about which build the test results applies to.

**Comment by ryanlong1004** [comment]
completed previously.  working directories, if already exist, are removed and re-cloned.
