### ISSUE TITLE
Push build/test logs, even if these fail

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#50]
Having any information at all, even when the build and/or test scripts fail is helpful.  

Currently, the commands to push build and test logs to esmf-test-artifacts are in the same job as the build and test themselves.  This means if they fail early, the logs are never pushed to esmf-test-artifacts.

One option is to **create separate jobs in the batch system to push the artifacts** -- and they should run even if the build/test jobs fail.  Often there are still error messages, etc. that can be pushed to esmf-test-artifacts.

**Comment by rsdunlapiv** [comment]
@ryanlong1004 @mark-a-potts I think this has been fixed.  Please confirm and if so we can close this one.

**Comment by ryanlong1004** [comment]
confirmed, closing.
