### ISSUE TITLE
Incorrect xyz.summary updating - not 100% trustworthy.

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-scripts#53]
I have noticed incorrect updating of an existing xyz.summary file can occur when multiple hashes are being tested in an interleaved fashion. Specifically what I see is during the release/8.2.0 testing, that lines in file `release_8.2.0/ESMF_8_2_0_beta_snapshot_21.summary` are being updated with information that comes from processing of *.summary files from configurations that are already running the next hash (ESMF_8_2_0_beta_snapshot_21-1-g86aff4e). 
The mechanism by which this happens seems to be through the processing on the separate machine specific branches. One incorrect update that I see is for the cheyenne/gfortran/9.1.0/openmpi/4.0.5 combo, but it comes in through commit https://github.com/esmf-org/esmf-test-artifacts/commit/ed54424dd67cc658f6b9644d5fbd0dcc7042847c which has commit message "update for test of gfortran_10.3.0_mpich3_g_release_8.2.0 with hash ESMF_8_2_0_beta_snapshot_21 on acorn". I see no update on the acorn lines, but a bunch of incorrect updates that all seem to be from the next hash that is already being tested.
The end effect is that really the xyz.summary tables in this situation are not 100% trustworthy. Even the table for the latest version might be messed up when there are still machines reporting for a previous version. Only after a full 24h period of no changes to the library repo the output is likely completely consistent in the latest xyz.summary table!

**Comment by theurich** [comment]
Further digging down into the details, the situation appears even worse when there are multiple branches being tested concurrently. I am seeing updates from one branch into the artifacts and summary of the other branch. This seems odd.

**Comment by rsdunlapiv** [comment]
@theurich @mark-a-potts reading my last comment there -- what is the meaning of the .summary file with no hash?  Isn't all testing against a specific hash?

**Comment by ryanlong1004** [comment]
Fixed.
