### ISSUE TITLE
Runs 'test_regrid_from_file_dryrun' twice.

### ISSUE THREAD

**Issue by ryanlong1004** [esmf-org/esmf-test-scripts#56]
In ```test_esmf.py```, line #248, writes the command ```python3 setup.py test_regrid_from_file_dryrun``` **twice** to the run script.

Is this intentional?

![image](https://user-images.githubusercontent.com/69773028/144727880-2b87cd1f-1724-4780-be9a-27ae4b562f1e.png)

**Comment by rokuingh** [comment]
@ryanlong1004 no reason that needs to be in there twice.
