### ISSUE TITLE
Allow summarizing test results from multiple branches

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-test-scripts#58]
During a release process we need to test multiple branches at once, e.g.:
- release/8.3
- develop

So, some platform config YAML files will be changed to list multiple branches.  In this case, results from testing each branch will be pushed to esmf-test-artifacts.  We found during the last release, however, that this confused the summarization script, and so ended up only testing the release branch.

We should turn on testing of several branches simultaneously, see where failures occur, and address them.

**Comment by rsdunlapiv** [comment]
Just to provide the motivation here -- when we branch for a release of ESMF, we want the develop branch to be open very quickly so the team can immediately start working on new developments concurrently while preparing for the release.

**Comment by ryanlong1004** [comment]
@rsdunlapiv isn't this already the case with the 'pull all' option?  Or are you talking about concurrency?

**Comment by rsdunlapiv** [comment]
@ryanlong1004 the basic idea is to be able to have multiple branches being tested on one or more machines, e.g.: in this line, you could add a list of several branches:
https://github.com/esmf-org/esmf-test-scripts/blob/f126e3c5543f0e75b263880bdfa0f3fd6f4687d3/config/cheyenne.yaml#L8

When we did this before during the release, we had some problems - I think they were related to summarization, but I am not 100% certain on the specifics of the issues.  @mark-a-potts can probably provide more insight.

However, what I would recommend is that you turn on testing of several ESMF branches on a couple of different platforms, and then monitor the summarization/merge script to make sure it is working as expected.  i..e, make sure the .summary text files are correctly produced under each branch directory.

**Comment by ryanlong1004** [comment]
Done.
