### ISSUE TITLE
Update Testing Wiki

### ISSUE THREAD

**Issue by ryanlong1004** [esmf-org/esmf-test-scripts#61]
Per @rsdunlapiv :

> I created two blank sections on the [ESMF wiki](https://github.com/esmf-org/esmf/wiki/Testing):
> 
> (1) Automated Cross-Platform Test Results Collection
> 
> (2) Adding a New Machine the Automated Testing
> 
> Can you please update these sections?  (1) should contain information about where the automated test artifacts are collected and how to use the summary tables and where the script is running that updates the summary tables.  (2) should have the steps required to add a new machine to the ESMF automated testing.
> 
> A user not familiar with our testing infrastructure should be able to use the steps in (2) to set up a new tested platform.
> 
> These should be relatively brief so that developers can get the critical info they need quickly - so not much more than a half page each.  Be sure to include links to esmf-test-artifacts, esmf-test-scripts, and esmf-branch-summary.

**Comment by theurich** [comment]
The WIKI is updated as to point to where the actual documentation is currently kept, in README.md files in the repo itself.
