### ISSUE TITLE
Commit message / folder structure error.

### ISSUE THREAD

**Issue by ryanlong1004** [esmf-org/esmf-test-scripts#64]
Commit message/folder structure incorrect for some cases.

This is causing a loss in reportable rows.

![image](https://user-images.githubusercontent.com/69773028/156462402-cb961228-c0ca-4ae7-af8e-05d2075c8df4.png)
![image](https://user-images.githubusercontent.com/69773028/156462460-c91497ef-8dad-4001-9e47-b3f0f85b52eb.png)

**Comment by ryanlong1004** [comment]
Another example.

Here, you should be able to change the "O" in the url to "g" to get the standard build results, but it doesn't exist.

![image](https://user-images.githubusercontent.com/69773028/158250895-d0111d55-7971-40c5-b57b-fc8e1d183ead.png)

**Comment by rsdunlapiv** [comment]
This is because there is a commit hash in the URL, and that commit hash might only contain the "O" combination.  In general, each commit should be thought of as a single incoming result for a single test combination (i.e., compiler, mpi, O/g) and either the "build" phase or the "test" phase.
