### ISSUE TITLE
extra_module and unload_module  not picked up by GAEA

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-scripts#79]
I have been analyzing the gaea/gfortran build failures. Currently these combos are failing the ESMF library build. It was however working fine for ESMF 8.3.0, so this was looking suspicious to me (potential test infrastructure issue).

Drilling down into it, I see that while config/gaea.yaml has 
```
       extra_module: "PrgEnv-gnu git/2.26.0"
       unload_module: PrgEnv-intel

```
under the gfortran section, it does not seem to show up under the actual [build.bat](https://github.com/esmf-org/esmf-test-artifacts/blob/23aecf963691993e8b695fb9032c13f0ece37918/develop/gfortran/8.3.0/O/mpiuni/None/out/build.bat)! This would explain why the build fails with what looks like the Intel compiler still being referenced by the Unicos style CC and ftn wrappers.

Notice that also the intel section in config/gaea.yaml does not seem to be picked up correctly (see [build.bat](https://github.com/esmf-org/esmf-test-artifacts/blob/23aecf963691993e8b695fb9032c13f0ece37918/develop/intel/2019.5/O/mpiuni/None/out/build.bat)). But it still works, because Intel is the default when you first log into GAEA anyway.

I did compare to other platforms, e.g. acron.yaml, and there it does seem to work correctly.

**Comment by rsdunlapiv** [comment]
The `extra_module` and `unload_module` need to be at the same indentation level as the `extra_env_variables`.  In gaea.yaml it looks like they need to be indented one more level.

I know this is subtle and it would be nice to have a validation of the YAMLs.  I'd like to find a way to provide a schema and check each push of the YAMLs against the schema, flagging any unexpected issues like this one.

**Comment by theurich** [comment]
Let me look through the yaml files that use this, and make sure it is correctly placed. Then I'll push the update. Nice it isn't anything complicated to fix. :-)

**Comment by rsdunlapiv** [comment]
@theurich sounds good, thanks for fixing these issues!

**Comment by theurich** [comment]
@rsdunlapiv one more question. So there is no sense here where an "extra_module:" that is on same level as say "versions:" under "intel:" applies to all Intel combos? I am asking because that is how it looks under cheyenne.yaml right now. But I will go and fix it and just duplicate the extra_module line if needed - if that is correct.

**Comment by rsdunlapiv** [comment]
Right, you'll have to duplicate it for now.  We could add it at multiple levels, which would give the maximum flexibility, but currently it checks only at the deeper level, right underneath a specific compiler version.

**Comment by rsdunlapiv** [comment]
If it's helpful, you can see the current logic here:
https://github.com/esmf-org/esmf-test-scripts/blob/607d4c647aedf49dba755433cb17e37199e61a17/python_scripts/matrix.py#L48

**Comment by theurich** [comment]
Got it. ... of course that means that practically cheyenne.yaml has been working fine without those extra_module's loaded.... which makes me want to take them out of the cheyenne.yaml file. Do you see a reason not to?

**Comment by rsdunlapiv** [comment]
I agree, they should be removed if they are not being used in the current results.

**Comment by theurich** [comment]
Okay, that should be done.
