### ISSUE TITLE
Store NUOPC proto test results in artifacts

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-scripts#81]
Currently the output (stdout & Log) from the automated NUOPC proto test runs are not stored under the artifacts repo. This makes it difficult to figure out the details when there are failures indicated in the NUOPC proto tests on a specific platform. 
I just pushed a change under the `nuopc-app-prototypes` repo where now the `./testProtos.sh` script will produce a directory that stores the relevant output files. Currently this directory is set to be called `NUOPC-PROTO-RESULTS`. This is a request to commit and push this directory to the artifacts repo (maybe under the existing `test` subdir?).

**Comment by rsdunlapiv** [comment]
@theurich these results should start collecting now.  Let's take a look tomorrow as new artifacts come in.

**Comment by theurich** [comment]
It looks like it is functioning very well. Great to have those results under the artifacts now. I am closing this issue.
