### ISSUE TITLE
Add ESMPy testing

### ISSUE THREAD

**Issue by bekozi** [esmf-org/esmf-test-scripts#9]
Distill correct ESMPy testing. @rokuingh provided these test targets:

> ESMPy test targets
>  (python setup.py <target>):
> - test: run the single core unit tests
> - test_parallel: run the parallel unit tests
> - test_regrid: run only the single core regridding unit tests
> - test_regrid_parallel: run only the parallel regridding unit tests
> - test_examples: run single core examples
> - test_examples: run parallel examples
> - test_examples_dryrun: retrieve the data files necessary to run the examples
> - test_regrid_from_file: run single core ESMPy enabled regrid from file tests
> - test_regrid_from_file_parallel: run parallel ESMPy enabled regrid from file tests
> - test_regrid_from_file_dryrun: retrieve data files necessary to run the regrid from file tests
> - test_all: run test, test_parallel, test_examples, test_examples_parallel targets

**Comment by bekozi** [comment]
CircleCI is build everything except `test_regrid_from_file`. @rokuingh these tests seem pretty intensive. Are they necessary/required? I wonder if they are something used primarily for development.

**Comment by rokuingh** [comment]
@bekozi, no these tests are not for development, but they are the same tests run by ESMF_RegridWeightGenCheck, just using the ESMPy interfaces. They are costly so maybe the best solution is to reduce the number of tests to something like 10, instead of the 100+ currently run.
